language: node_js

node_js: node

cache: yarn

after_success:
- yarn coveralls
- yarn package

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: cX62q8fanA+1BXidpVobsx6vkmD7mI7STJN2b/zD9TxLKa7EY4MpSI8t3JFnW0EaUxbiIwTJEjeftfDJhxey0kPvPgUxEAf3h5V7IoO6KSmCZ0I8xYdnNbMtKNBJqNj5USHupWyK5geZbIQ+GtjCr0k07G7Sm1zz9SaV3pmB/FZpPFsev8TukUPrGMyfa6AThS32EJXrNSTDEcewaxrCQN+5PylWlACKZ72v1MUBa9Lzxs7Rfd9god0jFqw29EBuCkpqmvgpThdG2sT0wFgAlodBFnW/DeVRyyfciAbLiMUKPTErNCbH51Hcndh3Wi7lGpjqhk+UeU9rMuF7br+BnmHy0eqr+vBAFSaVxnornrsebX0qO+Vgd/accM0VgI6UzIbrEZeRtKYpkZAf1y+gYFOA3ThafEp3PBBSJz1RI6hP03VuPx4GS2qCDfLm9nWBHR/pKMc9MAUuGiaEmeSXWwUGxLpM+B/9vzJGHrywSUXM/9NLb0Tqd35HElPKp2Vv39dYSASC/XQIhW696Gt2Ewkrg4Cqx5RTn7WlJBWXAvryVMDtOiZzgdaqk5aOUMie3Qe5bH5M6lwEGp/Rbo9rCFtSXDPQMbxiQrUuBVt3u0lX4BTynKVWagpDDfuOTm1Fl4CY50dwvmuZZmmtK0GLLQ/POL7LiOhX1XUoL4WL1sU=
    file:
      - "exoframe-linux"
      - "exoframe-macos"
      - "exoframe-win.exe"
    on:
      tags: true
      repo: exoframejs/exoframe
  - provider: npm
    email: yamalight@gmail.com
    api_key:
      secure: r+zLtddsRr47NmZUkH6nJCV9QIfVv3fwnkEltzW1SbKIKt1xtFek0CE8qxsFpZrlxUYkhTjiMbG47DLl8SajrJbbjZOKTy2SbMskERcMNff1rZOXSk00Sd8xSaEfbTIC6z7xuEJ07IQSlmJdo/K/EPpdvoHBJme9its5DcPj/duaWOb9Cxze6nF/6RDbSId4A4qWr0v4vp6ZT8XWVzSQm5gXvF/TKZnreF1TjReTmhJ5wN1fhIEKC7DlbOGJqiiKFEPXy2btwsfot6O9uOU4yUC8VrUM6N7dFTFogcHxNVKgZ1BQOEVt9KGAHhwM0Ky2cRHXztoG0jHy0cboTwVbjyN5/TEXeHOmipbARAhi7q8U7yPo9DW4SHIMX/Ffwv//Onj3NCLkxWjObef7mznMYu6QtMwoCJsQdRGw6aBQP6OXy3XD/bmXjjMjyNcNkbukFCUj+7vtwuTDX0BFscSCbgIAj0ysDWbffJph+BOdYvVyXgsSBnrdrBHMlqEi9XmtuSH9ETYPfi1KKvfNOouJvOlykLqWKnZUxw4RFnyuUs7C5CEUZijy+e3Iir4Exzu5HDVkP38UaTKBvDLb+9V8ZRs5DdkDF2xe6kzAj4zsm68axBWnaiHCG3Qv3gC5RyxEFy+dxJ9UCSSm1oycvnKR6sNauEi82v7v2S9udfGs1aU=
    on:
      tags: true
      repo: exoframejs/exoframe
  - provider: npm
    email: yamalight@gmail.com
    tag: next
    api_key:
      secure: r+zLtddsRr47NmZUkH6nJCV9QIfVv3fwnkEltzW1SbKIKt1xtFek0CE8qxsFpZrlxUYkhTjiMbG47DLl8SajrJbbjZOKTy2SbMskERcMNff1rZOXSk00Sd8xSaEfbTIC6z7xuEJ07IQSlmJdo/K/EPpdvoHBJme9its5DcPj/duaWOb9Cxze6nF/6RDbSId4A4qWr0v4vp6ZT8XWVzSQm5gXvF/TKZnreF1TjReTmhJ5wN1fhIEKC7DlbOGJqiiKFEPXy2btwsfot6O9uOU4yUC8VrUM6N7dFTFogcHxNVKgZ1BQOEVt9KGAHhwM0Ky2cRHXztoG0jHy0cboTwVbjyN5/TEXeHOmipbARAhi7q8U7yPo9DW4SHIMX/Ffwv//Onj3NCLkxWjObef7mznMYu6QtMwoCJsQdRGw6aBQP6OXy3XD/bmXjjMjyNcNkbukFCUj+7vtwuTDX0BFscSCbgIAj0ysDWbffJph+BOdYvVyXgsSBnrdrBHMlqEi9XmtuSH9ETYPfi1KKvfNOouJvOlykLqWKnZUxw4RFnyuUs7C5CEUZijy+e3Iir4Exzu5HDVkP38UaTKBvDLb+9V8ZRs5DdkDF2xe6kzAj4zsm68axBWnaiHCG3Qv3gC5RyxEFy+dxJ9UCSSm1oycvnKR6sNauEi82v7v2S9udfGs1aU=
    on:
      branch: develop
      repo: exoframejs/exoframe
