language: node_js

node_js: node

cache: yarn

after_success:
- yarn coveralls
- yarn package

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: cX62q8fanA+1BXidpVobsx6vkmD7mI7STJN2b/zD9TxLKa7EY4MpSI8t3JFnW0EaUxbiIwTJEjeftfDJhxey0kPvPgUxEAf3h5V7IoO6KSmCZ0I8xYdnNbMtKNBJqNj5USHupWyK5geZbIQ+GtjCr0k07G7Sm1zz9SaV3pmB/FZpPFsev8TukUPrGMyfa6AThS32EJXrNSTDEcewaxrCQN+5PylWlACKZ72v1MUBa9Lzxs7Rfd9god0jFqw29EBuCkpqmvgpThdG2sT0wFgAlodBFnW/DeVRyyfciAbLiMUKPTErNCbH51Hcndh3Wi7lGpjqhk+UeU9rMuF7br+BnmHy0eqr+vBAFSaVxnornrsebX0qO+Vgd/accM0VgI6UzIbrEZeRtKYpkZAf1y+gYFOA3ThafEp3PBBSJz1RI6hP03VuPx4GS2qCDfLm9nWBHR/pKMc9MAUuGiaEmeSXWwUGxLpM+B/9vzJGHrywSUXM/9NLb0Tqd35HElPKp2Vv39dYSASC/XQIhW696Gt2Ewkrg4Cqx5RTn7WlJBWXAvryVMDtOiZzgdaqk5aOUMie3Qe5bH5M6lwEGp/Rbo9rCFtSXDPQMbxiQrUuBVt3u0lX4BTynKVWagpDDfuOTm1Fl4CY50dwvmuZZmmtK0GLLQ/POL7LiOhX1XUoL4WL1sU=
    file:
      - "exoframe-linux"
      - "exoframe-macos"
      - "exoframe-win.exe"
    on:
      tags: true
      repo: exoframejs/exoframe
  - provider: npm
    email: yamalight@gmail.com
    api_key:
      secure: keo/yRt9B8WQ1RplW08J2zWBWZqgvannrWE/4Wgx1BJX2kskbT/sQAFg1rX5n6Pc0plv1+vcR9CRiDbZFrsscsTuzpKlYbgtlhh0YiGldPSLNySl6BXM8NvhOOZ/R9iunJgMzMhvy4dKZnzqOQLrl4p8HZQRp17qfkzy4ZJZsM4DcbJcoEJWEIgIyAR1x+I66HiA94/nDSpkhNYShOoPVJSgiSuxpTrzwKezW71TahdQH9Omx4ekdtOsbXN6CxtcxO+qgPg4RTtVYMCfTtv18QP5izT8iOA2sW7t7QjNpmyNxsnHN1p0LiLSze+lbN+wKvL4hz8U4zgzrY+fu5sB4iehdxoeI1IGvr43TU5c2SszTHNxunuFbhv1rClQHqe+iXuVreMujPR60FBWgovHGXhI+bn4n/P6TIpIOO/6WKW1pW76R+SSfgnLm4O4KO1epAc6ixGEEDgmInivPwa+snP347J0bxao7GLEocP3nxEopjeDDLXob6Il5MboRCZF/caW4FFzTpVphdRXuLy2VaGrn+5Q/YZvFX2/RiWRAh4BqG9ZcNdpYsaM/Zb4RP+JoZxzjCdUi6Yek/nTMudIuFSO2tW3fkbMRTjoJx7HE6+agfLEQGjBHUAIGH/DIKAWy7MrmhdIyWqZIQLPXcZb8KMU6+HOpztKdhekWiPHm3Q=
    on:
      tags: true
      repo: exoframejs/exoframe
  - provider: npm
    email: yamalight@gmail.com
    tag: next
    api_key:
      secure: keo/yRt9B8WQ1RplW08J2zWBWZqgvannrWE/4Wgx1BJX2kskbT/sQAFg1rX5n6Pc0plv1+vcR9CRiDbZFrsscsTuzpKlYbgtlhh0YiGldPSLNySl6BXM8NvhOOZ/R9iunJgMzMhvy4dKZnzqOQLrl4p8HZQRp17qfkzy4ZJZsM4DcbJcoEJWEIgIyAR1x+I66HiA94/nDSpkhNYShOoPVJSgiSuxpTrzwKezW71TahdQH9Omx4ekdtOsbXN6CxtcxO+qgPg4RTtVYMCfTtv18QP5izT8iOA2sW7t7QjNpmyNxsnHN1p0LiLSze+lbN+wKvL4hz8U4zgzrY+fu5sB4iehdxoeI1IGvr43TU5c2SszTHNxunuFbhv1rClQHqe+iXuVreMujPR60FBWgovHGXhI+bn4n/P6TIpIOO/6WKW1pW76R+SSfgnLm4O4KO1epAc6ixGEEDgmInivPwa+snP347J0bxao7GLEocP3nxEopjeDDLXob6Il5MboRCZF/caW4FFzTpVphdRXuLy2VaGrn+5Q/YZvFX2/RiWRAh4BqG9ZcNdpYsaM/Zb4RP+JoZxzjCdUi6Yek/nTMudIuFSO2tW3fkbMRTjoJx7HE6+agfLEQGjBHUAIGH/DIKAWy7MrmhdIyWqZIQLPXcZb8KMU6+HOpztKdhekWiPHm3Q=
    on:
      branch: develop
      repo: exoframejs/exoframe
