language: node_js

node_js: node

cache: yarn

after_success:
- yarn coveralls
- yarn package

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: cX62q8fanA+1BXidpVobsx6vkmD7mI7STJN2b/zD9TxLKa7EY4MpSI8t3JFnW0EaUxbiIwTJEjeftfDJhxey0kPvPgUxEAf3h5V7IoO6KSmCZ0I8xYdnNbMtKNBJqNj5USHupWyK5geZbIQ+GtjCr0k07G7Sm1zz9SaV3pmB/FZpPFsev8TukUPrGMyfa6AThS32EJXrNSTDEcewaxrCQN+5PylWlACKZ72v1MUBa9Lzxs7Rfd9god0jFqw29EBuCkpqmvgpThdG2sT0wFgAlodBFnW/DeVRyyfciAbLiMUKPTErNCbH51Hcndh3Wi7lGpjqhk+UeU9rMuF7br+BnmHy0eqr+vBAFSaVxnornrsebX0qO+Vgd/accM0VgI6UzIbrEZeRtKYpkZAf1y+gYFOA3ThafEp3PBBSJz1RI6hP03VuPx4GS2qCDfLm9nWBHR/pKMc9MAUuGiaEmeSXWwUGxLpM+B/9vzJGHrywSUXM/9NLb0Tqd35HElPKp2Vv39dYSASC/XQIhW696Gt2Ewkrg4Cqx5RTn7WlJBWXAvryVMDtOiZzgdaqk5aOUMie3Qe5bH5M6lwEGp/Rbo9rCFtSXDPQMbxiQrUuBVt3u0lX4BTynKVWagpDDfuOTm1Fl4CY50dwvmuZZmmtK0GLLQ/POL7LiOhX1XUoL4WL1sU=
    file:
      - "exoframe-linux"
      - "exoframe-macos"
      - "exoframe-win.exe"
    on:
      tags: true
      repo: exoframejs/exoframe
  - provider: npm
    email: yamalight@gmail.com
    api_key:
      secure: SgTIf407F2HqKjcC8Pebiwox8p6gJHWFfDT7wMf506Py9jMX2C9TpVTayWYz4IYr9o3au6xhpw2HJEhpMHGDV6eQMb0CZDsLAIiiDBL6j1zu9mxPMGJfqjWlvhE4nxV1c14eeIFbgRzU7cXZD4so1UY9AEWIMKW5mEowT06o03d7bqEp3eVlvx+PDFDgPUgHkoIGDRZtfYxsc4E+95pSdbsvt3bJcLpOVUZomijtDQ3lwKywfSPOEzDbpr6ikjrmqC4TazaQWgrHrbIkZhAwtjT3lbyhOCi/FCNZUF/LFlL/NzDo4VgL5lvxIABPEQkGIfM9q2RjyYCb1SBj6AKO+xX9F85DvAHsyQUs5w499ffO5xsjDoeZjv80JY36pzji11WJS6MlHFKqko1EX0xCm2vgOl7AvOkzOHM/3sznU+kuzGqYD2rsDAyiZf6+/0oIiNkCH6gv/jUrZNUAPxN0RPq9RdJrcV5u0mYY6yTwHjQv/ODZ6eL1nAaruDxeEZqkz00R9o7jCq2MquUuE4WZzVsxj/l7gG1bwxK6+GdEHRCCDUze15Wg76su1y1d1UcU3LeHrduD8ypifliWCewUZnD7YFWApVO7cLulbRnXEZErswePuJhGMO4rqVNzz0M1tHYUeFou1jOgUPsDlw2fJiAhVY76z28ESw5HqNJhTXE=
    on:
      tags: true
      repo: exoframejs/exoframe
  - provider: npm
    email: yamalight@gmail.com
    tag: next
    api_key:
      secure: SgTIf407F2HqKjcC8Pebiwox8p6gJHWFfDT7wMf506Py9jMX2C9TpVTayWYz4IYr9o3au6xhpw2HJEhpMHGDV6eQMb0CZDsLAIiiDBL6j1zu9mxPMGJfqjWlvhE4nxV1c14eeIFbgRzU7cXZD4so1UY9AEWIMKW5mEowT06o03d7bqEp3eVlvx+PDFDgPUgHkoIGDRZtfYxsc4E+95pSdbsvt3bJcLpOVUZomijtDQ3lwKywfSPOEzDbpr6ikjrmqC4TazaQWgrHrbIkZhAwtjT3lbyhOCi/FCNZUF/LFlL/NzDo4VgL5lvxIABPEQkGIfM9q2RjyYCb1SBj6AKO+xX9F85DvAHsyQUs5w499ffO5xsjDoeZjv80JY36pzji11WJS6MlHFKqko1EX0xCm2vgOl7AvOkzOHM/3sznU+kuzGqYD2rsDAyiZf6+/0oIiNkCH6gv/jUrZNUAPxN0RPq9RdJrcV5u0mYY6yTwHjQv/ODZ6eL1nAaruDxeEZqkz00R9o7jCq2MquUuE4WZzVsxj/l7gG1bwxK6+GdEHRCCDUze15Wg76su1y1d1UcU3LeHrduD8ypifliWCewUZnD7YFWApVO7cLulbRnXEZErswePuJhGMO4rqVNzz0M1tHYUeFou1jOgUPsDlw2fJiAhVY76z28ESw5HqNJhTXE=
    on:
      branch: develop
      repo: exoframejs/exoframe
