language: node_js

node_js: node

cache: yarn

after_success:
- yarn coveralls
- yarn package

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: cX62q8fanA+1BXidpVobsx6vkmD7mI7STJN2b/zD9TxLKa7EY4MpSI8t3JFnW0EaUxbiIwTJEjeftfDJhxey0kPvPgUxEAf3h5V7IoO6KSmCZ0I8xYdnNbMtKNBJqNj5USHupWyK5geZbIQ+GtjCr0k07G7Sm1zz9SaV3pmB/FZpPFsev8TukUPrGMyfa6AThS32EJXrNSTDEcewaxrCQN+5PylWlACKZ72v1MUBa9Lzxs7Rfd9god0jFqw29EBuCkpqmvgpThdG2sT0wFgAlodBFnW/DeVRyyfciAbLiMUKPTErNCbH51Hcndh3Wi7lGpjqhk+UeU9rMuF7br+BnmHy0eqr+vBAFSaVxnornrsebX0qO+Vgd/accM0VgI6UzIbrEZeRtKYpkZAf1y+gYFOA3ThafEp3PBBSJz1RI6hP03VuPx4GS2qCDfLm9nWBHR/pKMc9MAUuGiaEmeSXWwUGxLpM+B/9vzJGHrywSUXM/9NLb0Tqd35HElPKp2Vv39dYSASC/XQIhW696Gt2Ewkrg4Cqx5RTn7WlJBWXAvryVMDtOiZzgdaqk5aOUMie3Qe5bH5M6lwEGp/Rbo9rCFtSXDPQMbxiQrUuBVt3u0lX4BTynKVWagpDDfuOTm1Fl4CY50dwvmuZZmmtK0GLLQ/POL7LiOhX1XUoL4WL1sU=
    file:
      - "exoframe-linux"
      - "exoframe-macos"
      - "exoframe-win.exe"
    on:
      tags: true
      repo: exoframejs/exoframe
  - provider: npm
    email: yamalight@gmail.com
    api_key:
      secure: tEPQY2HBJSh1inH5xDpwDSXjDkDDKdYtfMKudF4ewE6IG2rB8IdmGPftsoR/MI6kI1X8G95X6dFCgm7EmtlWQ6lHETEBq5JjvKi6R3Rw0gqt+NEe2mBYLjc4wWdme067mYu4DqMej5RWoYTteCvqudSGdpucvx9uf7hIup9beyuA6gdBGrA56UCZLGsJCErFrD/He3ER8d5qwbqEQ88QDbvrvkBy1FmWy5PkaQVavz9E3SuJEb+b7e3aRLIFFJMxXyMdwGru/b6YifSVv9Y+vhTu/te5NLQ3W5AQIwvxw6hXT2pIIxZEMWElf95ieR5ZAQz9KkesOJ7lvB1mO2PBInu5NuvPEQDcSAg5OKZzuxxeMWcDy229ywvTVGJw4yme8PrMAyj2mxxut6uB0wKnEZuPribCElZzkIyIDCClzLiG/VlKAfEpEYDbneXJpVOlXZoX8vbOVjHFBYS0OnKnmklM6W56ExttW4HFyYGivCbdZab5nnRAF0zFQOFVLnf562JMfD2daQG7fVoqyp2MAqJhSPB4w4nDtz+/8eyWYl9T8s4sEYrN5moPR30+//XwZR10irCG/LTpfF+aYoJEHNqqK0iK7+H3WLKPfqKVCp4mt4lIdkRKb098pDpwUq8Au/0tr8qecnk5Qq1vEQvAaedryFG6aR0ppM6m3y1gOs8=
    on:
      tags: true
      repo: exoframejs/exoframe
  - provider: npm
    email: yamalight@gmail.com
    tag: next
    api_key:
      secure: ElnoOpPnhjA8MAOzFQJEmKXu1tVGO6QmmqT7nUHH7O8fWGCjZ73bMD+ubVEB+A/lHF40iIedvyBecu7kNdn4hIw8nN5zpKFZ5I0FqhozOXh1xhYimdgbO5jizV27+9UA3U0gQpk74xJ9t3IfmgmpyjoY1j7YovytwsuIRNChvwwR4Hvc2Vuuyq+2Bb9IWr9Aq2K9SFxvQ9WQ/1pAKx96uHwEDw8TOFTm1L/i+7ui4jHiay+D1NL0RJx4TPQMdI3qVLe8837VLkrQQl2ltiOfuCpnEVlk3m9x8/l/8SRkof8iXoneEyytzF85nzodRpu+qa4/vtN6s3N0nXgvjsXJMVqFhLl/4Dx92cTdTbtCYZuXeBoAkfyUC2yxQeAh7o+pFDjYJZGpiZo0rBCmx82HyLiVyEq/r/3m56UMnYDcLBU9BgWo666VVljjH/zcGpJCBxq6jthm6rdiBTCRBorQtg6bpUu79WJF1l54m0LiEzBmcLIedxQdHQi5fl/yr1gMCv/wCjeiQCiC2xmcUq4TTlFlpoNGcOlTe+1wT4HgPjjv6juo/wPV0uSsDKMeafeXJuTuJshd83kzUQRuCbrxKPH5heNZ1MqyOQ4TB7b68LyFH9gmcojETjzQVlVS8wn7s5i64o0lb7u5Ua59VpkCQw3063EAig8n6iU1tm2pJdA=
    on:
      branch: develop
      repo: exoframejs/exoframe
